services:
  - type: web
    name: youtube-stream-api
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: YOUTUBE_API_KEY
        value: AIzaSyDYFu-jPat_hxdssXEK4y2QmCOkefEGnso
      - key: USER_AGENT
        value: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
