services:
  - type: web
    name: Ytdl
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      playwright install chromium
    startCommand: python main.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    plan: free
